### ISSUE TITLE
Low-hanging fruit: split functions and take fewer loops through fonts

### ISSUE THREAD

**Issue by thundernixon** [thundernixon/varfont-prep#5]
Currently, varfont-prep is opening fonts, doing a small task, saving them, and closing them ... _and then repeating that_ for the next small task.

This is super inefficient and will be relatively easy to refactor with a bit of patience.

**Comment by arrowtype** [comment]
Turns out, you can open fonts _once_ into a list or dict, then manipulate them in separate loops.

I did this, this week, and as of https://github.com/arrowtype/varfont-prep/commit/3872d9df7da8e85d24a95ca6728553ab04f7df85, the main script now runs about 10x faster. (Improvements are bigger for larger fonts – Recursive's prep time went from ~40 minutes to ~3 minutes.)
